### ISSUE TITLE
大佬有homework资源吗

### ISSUE THREAD

**Issue by dayangyouxia1** [n0rea5on/CS61A-2020-Fall-Metarials-Mirror#1]
大佬有homework资源吗

**Comment by Lsyx-Good** [comment]
在HW里面不是有嘛

**Comment by dayangyouxia1** [comment]
> 在HW里面不是有嘛

只有前五次的作业，后面的作业缺失了

**Comment by Lsyx-Good** [comment]
看了一下确实是

**Comment by Lsyx-Good** [comment]
[这里有](https://github.com/kckckcd/cs-61a-fall2020-/tree/main/homework)

**Comment by dayangyouxia1** [comment]
> [这里有](https://github.com/kckckcd/cs-61a-fall2020-/tree/main/homework)

十分感谢！
